jobs/urls.py
################################################################################ 
# JobBoard: a simple Django-based job board
# Copyright (c) 2012, CandidOak Concepts
# All rights reserved.
#                    
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
################################################################################

from django.conf.urls import patterns, include, url
from jobs.feeds import LatestJobsFeed
from jobs.sitemap import JobPostSitemap
from django.contrib.sitemaps.views import sitemap

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

sitemaps = {
    'jobs': JobPostSitemap,
}

urlpatterns = patterns('jobs.views',
    url(r'^$', 'index', {}, 'home_page'),
    url(r'^jobs/$', 'index', {}, 'jobs_home_page'),
    url(r'^jobs/view/(?P<job_id>\d+)/$', 'job_detail_old', {}),
    url(r'^jobs/(?P<job_id>\d+)/(?P<job_slug>[-\w]+)/$', 'job_detail', {}, 'job_detail_view'),
    url(r'^jobs/approve/(?P<job_id>\d+)/$', 'approve_job', {}),
    url(r'^jobs/alert/$', 'job_alert', {}),
    url(r'^jobs/alert/subscribe/confirm/$', 'job_alert_subscribe_confirm', {}),
    url(r'^jobs/alert/thanks/confirm/$', 'job_alert_confirm_thanks', {}),
    url(r'^jobs/alert/thanks/$', 'job_alert_thanks', {}),
    url(r'^jobs/search/$', 'search_jobs', {}),
    
    url(r'^login/$', 'login', {}),
    url(r'^logout/$', 'logout', {}),
    url(r'^signup/$', 'signup', {}),
    
    url(r'^contact/$', 'contact', {}),
    url(r'^contact/thanks/$', 'contact_thanks', {}),
    
    url(r'^user/home/$', 'user_home', {}),
    url(r'^user/submit_job/$', 'submit_job', {}),
    url(r'^user/jobs/edit/(?P<job_id>\d+)/$', 'update_job', {}),
    url(r'^user/jobs/view/(?P<job_id>\d+)/$', 'user_job_detail', {}),
    url(r'^user/jobs/delete/(?P<job_id>\d+)/$', 'delete_job', {}),
    
    url(r'^staff/home/$', 'staff_home', {}),
    url(r'^staff/subscribers/$', 'view_subscribers', {}),
    
    url(r'^terms_and_conditions/$', 'terms_conditions', {}),
    
    url(r'^feeds/jobs/latest/$', LatestJobsFeed()),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}),    
)

techjobs/urls.py
################################################################################ 
# JobBoard: a simple Django-based job board
# Copyright (c) 2012, CandidOak Concepts
# All rights reserved.
#                    
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
################################################################################

from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('jobs.views',
    url(r'^', include('jobs.urls')),
    url(r'^account/', include('django.contrib.auth.urls')), # do not remove. For the custom /templates/registration/... files
)

jobs/models.py
################################################################################ 
# JobBoard: a simple Django-based job board
# Copyright (c) 2012, CandidOak Concepts
# All rights reserved.
#                    
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
################################################################################

import datetime
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

COUNTRY_CHOICES = (
    ('KE', 'Kenya'),
    ('TZ', 'Tanzania'),
    ('UG', 'Uganda'),
)

JOB_TYPE_CHOICES = (
    ('FULLTIME', 'Full Time'),
    ('PARTTIME', 'Part Time'),
)

################################################################################
## Models
################################################################################

class JobType(models.Model):
    """
    An available job type for working, be it a contract, full time or part time.

    These appear on drop-down forms for those submitting job posts.

    Field Attributes:
      name: The name of the job type
    """
    
    name = models.CharField(max_length=80)
    
    def __unicode__(self):
        return self.name
        

class JobCountry(models.Model):
    """
    An available job country for working, be it Kenya, Uganda or Tanzania.

    These appear on drop-down forms for those submitting job posts.

    Field Attributes:
      country_name: The name of the country
      short_desc: The short description of country i.e. KE, UG or TZ
    """
    
    country_name = models.CharField(max_length=60)
    short_desc = models.CharField(max_length=10)
    
    def __unicode__(self):
        return self.country_name


class JobPost(models.Model):
    """
    A post for an available job that people can apply to.

    These are usually user-submitted, and then approved by an
    administrator.  Once they are approved, they should show up on the
    job listing until the time they expire.

    Field Attributes:
        job_type:   Type of job i.e. Contract, Part time or full time.
        job_title:  Title of the job offered
        job_description:    Description of this job
        job_country:    Country where this job is offered
        company_name:   Name of the company posting the job
        company_url:    URL of the company website
        apply_information:  Information on how to apply for the job
        apply_email:    An email address relevant to this job (probably for 
                        contact purposes)
        date_posted:    The timestamp for when this post was submitted
        posted_by:  The user ID of the person or company posting the job
        approved:   Whether or not this application was approved to be
                    listed on the site.
        paid:       Whether or not this application has been paid for.
        post_anon:  Post anonymously
    """
    
    job_type = models.ForeignKey(JobType)
    job_title = models.CharField(max_length=200)
    job_description = models.TextField('Job Description')
    job_req = models.TextField('Job Requirements')
    job_country = models.ForeignKey(JobCountry)
    company_name = models.CharField(max_length=256)
    company_url = models.URLField()
    company_profile = models.TextField('Company Profile')
    apply_information = models.TextField('How to apply')
    apply_email = models.EmailField()
    job_deadline = models.DateField('Deadline Date')
    date_posted = models.DateTimeField('Date posted', auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    posted_by = models.ForeignKey(User)
    approved = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    post_anon = models.BooleanField(default=False)
    slug = models.SlugField(max_length=200, blank=True, null=True, help_text='Unique value for job page url, created from job title.')
    
    class Meta:
        ordering = ['-date_posted']
        #unique_together = (('job_title', 'company_name'),)
    
    def __unicode__(self):
        return "%s - %s" % (self.company_name, self.job_title)
    
    @models.permalink    
    def get_absolute_url(self):
        return ('job_detail_view', (), {
            'job_id': self.id,
            'job_slug': self.slug,
        }) 
        
    def save(self, *args, **kwargs):
        if self.job_title:
            self.slug = slugify(self.job_title)
            super(JobPost, self).save(*args, **kwargs) # Call the "real" save() method.
        
        
class JobSubscriber(models.Model):
    """
    Subscriber who receives job alerts
    """
    subscriber_email = models.EmailField(max_length=254, unique=True)
    is_activated = models.BooleanField(default=False)
    key = models.CharField(max_length=32)
    
    def __unicode__(self):
        return self.subscriber_email
        
        
class JobTag(models.Model):
    """
    Tags used to categorize jobs
    """
    
    tag_name = models.CharField(max_length=30, unique=True)
    jobposts = models.ManyToManyField(JobPost)
    
    def __unicode__(self):
        return self.tag_name
        
    class Meta:
        ordering = ('tag_name',)
        

class JobPostView(models.Model):
    """
    Track the number of views per job post
    """
    
    jobpost = models.ForeignKey(JobPost, related_name='jobpostviews')
    ip = models.CharField(max_length=40)
    created = models.DateTimeField(default=datetime.datetime.now())

templates/includes/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block meta_desc %}Tech jobs and resumes posted daily in East Africa. Offers FREE job posting, resume database, custom data feeds, daily job alerts and more.{% endblock %}">
    <meta name="keywords" content="tech jobs in kenya, tech jobs in tanzania, tech jobs in uganda, tech jobs in east africa, it jobs, jobs in east africa, java jobs, python jobs, ruby jobs">
    <meta name="author" content="CandidOak Concepts">
    <meta name="google-site-verification" content="aVyFjpX4vhT6VwJmsmvId_RGfKcn8gRoib3KWaVR9Dg" />
    
    <title>{% block title %}Home{% endblock %} | TechJobsBistro</title>
    <link rel="icon" type="image/png" href="{{ STATIC_URL }}images/favicon.png">
    
    <!-- CSS Styles-->
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery-ui.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/general.css">
    
    <!-- JS Scripts --> 
    <script src="{{ STATIC_URL }}js/jquery-1.8.2.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/jquery.autocomplete.pack.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/jquery.form.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/jquery.validate.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/jcookie.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/jquery.bootstrap.confirm.popover.js" type="text/javascript"></script>
    
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-37133935-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
	
	<script type="text/javascript">
    jQuery.noConflict();
    jQuery(document).ready(function () {
        
        jQuery('.validation').blur(function () {
            if (jQuery(this).valid()) {
                var nm = jQuery(this).attr("name");
                jQuery('#label' + nm).removeClass('no');
                jQuery('#label' + nm).addClass('yes');
            }
        }); 
        
        var skills = jQuery(".skills").children("li").length;
        var visible = skills - jQuery(".skills").children("li").children("div").children(".hidden").length;
        var maxSkills = 10;
        var selected = skills - 3;
        
        jQuery(".hidden").parent().parent().hide();
        jQuery("#addskill").click(function () {
            visible++;
            if (skills == visible) {
                jQuery(this).fadeOut();
            }
            if (skills >= visible) {
                jQuery(".skills #skill" + visible).removeClass("hidden");
                jQuery(".skills #skill" + visible).parent().parent().show();
            }
            return false;
        }); 
        
        jQuery("#id_job_deadline").datepicker({
            dateFormat:'yy-mm-dd',
			changeMonth: true,
            changeYear: true,
            onSelect:function (dateText, inst) {
                jQuery('#labelexpdate').removeClass('yes').removeClass('no').addClass('yes')
            }
        }); 
        
        // Add a popup to anchor tags to confirm action
        jQuery('a.confirm').confirmDialog({
            message: '<strong>Do you really want to delete this entry</strong>',
            cancelButton: 'Cancel'
        });

        
        jQuery("input[name=anon]").click(function () {
            if (jQuery("input[name=anon]").attr("checked") && jQuery("input[name=company_name_value]").val() != "Anonymous") {
                jQuery("#companyName").val('Anonymous');
                jQuery("#companyName").addClass("disabled");
                jQuery("#companyName").attr("disabled", true);
                jQuery("#companyName").css("color", '#000');
                jQuery('#labelcompany_name_value').removeClass('yes').removeClass('no').addClass('yes');
                jQuery("input[name=anon]").attr("checked", true);
            } else {
                jQuery("#companyName").val('e.g. CandidOak Ltd.');
                jQuery("#companyName").removeClass("disabled");
                jQuery("#companyName").attr("disabled", false);
                jQuery("#companyName").css("color", '#CCC');
                jQuery('#labelcompany_name_value').removeClass('yes').removeClass('no').addClass('no');
                jQuery("input[name=anon]").attr("checked", false);
            }
        }); 
        
        jQuery("input[name=noexpire]").click(function () {
            if (jQuery("input[name=noexpire]").attr("checked") && jQuery("#date").val() != "No expiry date") {
                jQuery("#date").val('No expiry date');
                jQuery("#date").addClass("disabled");
                jQuery("#date").attr("disabled", true);
                jQuery('#labelexpdate').removeClass('yes').removeClass('no').addClass('yes');
                jQuery("input[name=noexpire]").attr("checked", true);
            } else {
                jQuery("#date").val('yyyy/mm/dd');
                jQuery("#date").removeClass("disabled");
                jQuery("#date").attr("disabled", false);
                jQuery('#labelexpdate').removeClass('yes').removeClass('no').addClass('no');
                jQuery("input[name=noexpire]").attr("checked", false);
            }
        });
        
    });
    </script>
</head>

<body>

    <div class="container-fluid">
        <div class="span1"></div>
        
        <div class="span10">
    
            <!-- HEADER SECTION-->
            <div class="row-fluid">
                <div class="span12">
                    <div class="row-fluid header">
                        <div class="span4 logo">
                            <a href="/"><img src="{{ STATIC_URL }}images/logo.png" alt="TechJobsBistro logo" height="70" /></a>
                        </div>
                        
                        <div class="span4 offset4 tagline">
							<!--<span><h3>Tech Jobs Bistro Portal</h3><br/>-->
							{% if user.is_authenticated %}
							
							Welcome, {{ user.username }}. 
							
								{% if user.is_staff %}
									<a href="/staff/home">Control Panel</a> | <a href="/logout">Logout</a>
								{% else %}
									<a href="/user/home">Manage Listings</a> | <a href="/logout">Logout</a>
								{% endif %}
														
							{% else %}
							
							To post a job, <a href="/login"><strong>login</strong></a>
                             or <a href="/signup"><strong>create an account</strong></a>
                             </span>
							 
							{% endif %}
							
							<br/><br/>
							<div class="site_search">
								<form role="search" method="get" action="/jobs/search/">
									<span>
										<input  type="text" 
												onblur="if (this.value == '') {this.value = 'Search by keyword';}" 
												onfocus="if (this.value == 'Search by keyword') {this.value = '';}" 
												value="Search by keyword" 
												id="search_box" 
												name="s" 
												autocompletefn="off" 
												class="ac_input">
										<button class="icon icon_search" type="submit" name="submit"></button>
									</span>
								</form>
							</div>
                        
                        </div>
                    </div>
                    
                    <!-- Menu -->
                    <div class="row-fluid menu">
                        <div class="span12 category_menu black">
                            <ul>
                                <li class="cat-item-all current-cat">
                                    <a href="/jobs">All Jobs</a>
                                </li>
                                <li class="cat-item-5 ">
                                    <a href="/jobs/alert">Job Alerts</a>
                                </li>
                                <li class="cat-item-4 ">
                                    <a href="/contact">Contact Us</a>
                                </li>
                                <li class="rss">
                                    <a href="/feeds/jobs/latest/"><img src="{{ STATIC_URL }}images/icon.rss.png"></a>
                                </li>
                            </ul>
                        </div>
                    </div><!-- /Menu -->
                </div>
                
                
            </div><!-- /HEADER SECTION-->
            
            <!-- CONTENT SECTION-->
            <div class="row-fluid">
                
                <!-- BODY CONTENT -->
                <div class="span9">
                    <div class="focus">
                        {% block content %}{% endblock %}
                    </div><!-- /focus -->
                </div>
                
                {% block sidebar %}
                    {% if user.is_authenticated %}
                        {% if user.is_staff %}
					        {% include 'includes/sidebar_admin.html' %}
					    {% else %}
					        {% include 'includes/sidebar_user.html' %}
					    {% endif %}
                    {% else %}
				        {% include 'includes/sidebar.html' %}
				    {% endif %}
				{% endblock %}
                
            </div><!-- /CONTENT SECTION-->
            
			{% block footer %}
            <!-- FOOTER SECTION-->
            <div class="row-fluid footer">
                <div class="span12">
                
                    <div class="span6 copyright">
                        <p>&copy; Copyright {% now "Y" %} TechJobsBistro. All rights reserved.</p>
                    </div>
                    
                    <div class="span6 menu">
                        <ul>
                            <li><a href="/jobs">Home</a></li>
                            <li><a href="/login">Login</a></li>
                            <li><a href="/signup">Signup</a></li>
                            <li><a href="/terms_and_conditions">Terms and Conditions</a></li>
                            <li><a href="/contact">Contact Us</a></li>         
                        </ul>
                    </div>
                    
                    <div class="seo">
                        <p>TechJobsBistro.com is an Information Technology job site in East Africa, connecting job seekers with employers looking to hire. Every day, hundreds of new job vacancies are listed from the region's top employers.</p>
                    </div>
 
                </div>
            </div><!-- /FOOTER SECTION-->
			{% endblock %}
        
        </div>
        
        <div class="span1"></div>
    </div><!-- /Container-->
<script type="text/javascript" src="{{ STATIC_URL }}js/tiny_mce/tiny_mce.js"></script>


<script type="text/javascript">
	tinyMCE.init({
			mode : "textareas",
			theme_advanced_path : false,
			theme_advanced_buttons1 : "bold,italic,|,bullist,numlist,",
	});
</script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
</body>

</html>

templates/includes/sidebar.html
{% load country_jobs %}
{% load i18n %}
{% load url from future %}

<!-- SIDEBAR CONTENT -->
                <div class="span3 sidebar">
                    <ul>
						<li class="cell action">
                            <p>Post a job FREE for 30 days</p>
                            <a class="button blue xlarge" href="/user/submit_job">
                                <span>Post a job</span>
                            </a>
                        </li>
                        
                        <!--<li class="quicksearch">
                            <form role="search" method="get" action="/jobs/search/">
                                <span>
                                    <input  type="text" 
                                            onblur="if (this.value == '') {this.value = 'Search by keyword';}" 
                                            onfocus="if (this.value == 'Search by keyword') {this.value = '';}" 
                                            value="Search by keyword" 
                                            id="search_box" 
                                            name="s" 
                                            autocompletefn="off" 
                                            class="ac_input">
                                    <button class="icon icon_search" type="submit" name="submit"></button>
                                </span>
                            </form>
                        </li>-->
                        
                        <li><h2 class="widgettitle">Job count per Country</h2></li>
                        
                        {% show_country_job_count %}
                                                      
                        <li class="about">
                            <h2 class="widgettitle">About Us</h2>
                            TechJobsBistro.com is a job portal exclusively for tech professionals in East Africa, connecting job seekers with employers looking to hire. Every day, hundreds of new job vacancies are listed from the region's top employers.                 
                        </li>
                        
                        <li class="custom">
                            <h2 class="widgettitle">Daily Job Alerts</h2>
                            Get notified when a new position is available. Click <a href="/jobs/alert/">here</a>                      
                        </li>
                        
                    </ul>
                </div>

templates/includes/sidebar_admin.html
{% load country_jobs %}
{% load i18n %}
{% load url from future %}

<!-- SIDEBAR CONTENT -->
                <div class="span3 sidebar">
                    <ul>
						<li class="cell action">
                            <p>Post a job FREE for 30 days</p>
                            <a class="button blue xlarge" href="/user/submit_job">
                                <span>Post a job</span>
                            </a>
                        </li>
					
                        <li><h2 class="widgettitle">My Control Panel</h2></li>
                        
                        <li>
                            <ul class="tablets">
                                <li><a href="/user/submit_job">Post a job</a></li>
                                <li><a href="#">Review job listings</a></li>
                                <li><a href="/staff/subscribers">Subscribers</a></li>
                                <li><a href="{% url 'password_change' %}" title="Change password">Change password</a></li>
                            </ul>
                        </li>
                        
                        <!--<li class="quicksearch">
                            <form role="search" method="get" action="#">
                                <span>
                                    <input  type="text" 
                                            onblur="if (this.value == '') {this.value = 'Search by keyword';}" 
                                            onfocus="if (this.value == 'Search by keyword') {this.value = '';}" 
                                            value="Search by keyword" 
                                            id="search_box" 
                                            name="s" 
                                            autocompletefn="off" 
                                            class="ac_input">
                                    <button class="icon icon_search" type="submit" name="submit"></button>
                                </span>
                            </form>
                        </li>-->
                        
                        <li><h2 class="widgettitle">Job count per Country</h2></li>
                        
                        {% show_country_job_count %}
                                                      
                        <li class="about">
                            <h2 class="widgettitle">About Us</h2>
                            TechJobsBistro.com is an Information Technology job site in East Africa, connecting job seekers with employers looking to hire. Every day, hundreds of new job vacancies are listed from the region's top employers.                 
                        </li>
                        
                        <li class="custom">
                            <h2 class="widgettitle">Daily Job Alerts</h2>
                            Get notified when a new position is available. Click <a href="/jobs/alert/">here</a>                      
                        </li>
                        
                    </ul>
                </div>

templates/includes/sidebar_user.html
{% load country_jobs %}
{% load i18n %}
{% load url from future %}

<!-- SIDEBAR CONTENT -->
                <div class="span3 sidebar">
                    <ul>
						<li class="cell action">
                            <p>Post a job FREE for 30 days</p>
                            <a class="button blue xlarge" href="/user/submit_job">
                                <span>Post a job</span>
                            </a>
                        </li>
					
                        <li><h2 class="widgettitle">My Control Panel</h2></li>
                        
                        <li>
                            <ul class="tablets">
                                <li><a href="/user/submit_job">Post a job<span>7</span></a></li>
                                <li><a href="/user/home">My job listings<span>6</span></a></li>
                                <li><a href="{% url 'password_change' %}" title="Change password">Change password<span>6</span></a></li>
                            </ul>
                        </li>
                        
                        <!--<li class="quicksearch">
                            <form role="search" method="get" action="#">
                                <span>
                                    <input  type="text" 
                                            onblur="if (this.value == '') {this.value = 'Search by keyword';}" 
                                            onfocus="if (this.value == 'Search by keyword') {this.value = '';}" 
                                            value="Search by keyword" 
                                            id="search_box" 
                                            name="s" 
                                            autocompletefn="off" 
                                            class="ac_input">
                                    <button class="icon icon_search" type="submit" name="submit"></button>
                                </span>
                            </form>
                        </li>-->
                        
                        <li><h2 class="widgettitle">Job count per Country</h2></li>
                        
                        {% show_country_job_count %}
                                                      
                        <li class="about">
                            <h2 class="widgettitle">About Us</h2>
                            TechJobsBistro.com is a job portal exclusively for tech professionals in East Africa, connecting job seekers with employers looking to hire. Every day, hundreds of new job vacancies are listed from the region's top employers.                  
                        </li>
                        
                        <li class="custom">
                            <h2 class="widgettitle">Daily Job Alerts</h2>
                            Get notified when a new position is available. Click <a href="/jobs/alert/">here</a>                      
                        </li>
                        
                    </ul>
                </div>